# Generated by Django 3.1.5 on 2021-03-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
