# Generated by Django 3.1.5 on 2021-02-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
