# Generated by Django 3.1.5 on 2021-03-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_auto_20210309_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed')], max_length=10)),
                ('client_id', models.IntegerField()),
                ('client', models.CharField(max_length=150)),
                ('bonus', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
