# Generated by Django 3.1.5 on 2021-02-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='client_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchases',
            name='point',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchases',
            name='product',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='service',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
