# Generated by Django 3.1.5 on 2021-09-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='services',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
