# Generated by Django 3.1.5 on 2021-03-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_auto_20210228_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='my_bonus',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refer_bonus',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='served',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=612345678, max_length=200),
            preserve_default=False,
        ),
    ]
