# Generated by Django 3.1.5 on 2021-03-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_auto_20210303_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchases',
        ),
    ]
