# Generated by Django 3.1.5 on 2021-10-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='event',
            field=models.CharField(default='new event', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(default='new style', max_length=100),
            preserve_default=False,
        ),
    ]
