# Generated by Django 3.1.5 on 2021-03-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_delete_purchases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('client', models.CharField(max_length=200, null=True)),
                ('worker', models.CharField(max_length=200, null=True)),
                ('product', models.JSONField(blank=True, null=True)),
                ('service', models.JSONField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('point', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
