# Generated by Django 3.1.5 on 2021-03-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0007_purchases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='product',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='service',
        ),
        migrations.AddField(
            model_name='purchases',
            name='worker_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
